const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync('index.html', 'utf8');
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m => m[1]);
scripts.forEach(script => new vm.Script(script));
const main = scripts.find(script => script.includes('function parseFinalAuditCsv'));
const functions = [...main.matchAll(/^    (?:async )?function \w+\([^]*?^    }/gm)].map(m => m[0]).join('\n');
const constants = ['dockLayoutBlocks', 'dockZoneLabels'].map(name => main.match(new RegExp('    const ' + name + ' = \\[[^]*?^    \\];', 'm'))[0]).join('\n');
const ctx = vm.createContext({ console, data: {docas:92} });
vm.runInContext(constants + '\n' + functions, ctx);
const run = code => vm.runInContext(code, ctx);
const header = 'Shipment ID,Placa,Data auditoria,ID da rota,Estado,Rep auditoria\n';
ctx.csv = header + '1,ABC1D23,30/09/2026 10:00:00,A1_AM1 | 123,A mais,Teste\n1,ABC1D23,30/09/2026 10:00:00,A1_AM1 | 123,A mais,Teste\n2,ABC1D23,30/09/2026 10:01:00,A1_AM1 | 123,Faltante,Teste';
const parsed = run('parseFinalAuditCsv(csv)');
assert.equal(parsed.packages, 2); assert.equal(parsed.duplicates, 1);
assert.equal(parsed.rows[0].aMais, 1); assert.equal(parsed.rows[0].faltantes, 1);
ctx.csv += '\n1,ABC1D23,30/09/2026 10:02:00,A1_AM1 | 123,Correto,Teste';
assert.equal(run('parseFinalAuditCsv(csv).rows[0].aMais'), 0);
ctx.csv += '\n3,ABC1D23,01/10/2026 10:02:00,A1_AM1 | 123,Faltante,Teste';
assert.throws(() => run('parseFinalAuditCsv(csv)'), /único dia/);
ctx.csv = header + '1,ABC1D23,30/09/2026 10:00:00,A1_AM1 | 123,Desconhecido,Teste';
assert.throws(() => run('parseFinalAuditCsv(csv)'), /inválidos/);
for (const [dock, side] of [[1,'Lado Heineken'],[14,'Lado Heineken'],[18,'Lado Central'],[45,'Lado Central'],[51,'Lado Parede'],[85,'Lado Parede'],[86,'Line Hall'],[92,'Line Hall'],[46,'Sem lado identificado']]) {
 ctx.dock = dock; assert.equal(run('auditSideForDock(dock)'), side);
}
ctx.source = { data: '30/09/2026', extracao: [{rota:'A1_AM1', idRota:'123', doca:'23'}], aduanaFechamentoFinal: parsed };
let model = run('packageClosureModel(source)');
assert.equal(model.groups.find(g => g.label === 'Lado Central').aMais, 1);
assert.equal(model.faltantes, 1);
ctx.source.extracao[0].idRota = '999';
assert.equal(run('packageClosureModel(source).groups.find(g=>g.label==="Sem lado identificado").rows.length'), 1);
ctx.source.extracao[0].idRota = '';
assert.equal(run('packageClosureModel(source).groups.find(g=>g.label==="Lado Central").rows.length'), 1);
ctx.source = {data:'01/10/2026', aduanaFechamentoFinal:parsed, baseAduana:[{rota:'A1_AM1',aduanaAMais:'2',aduanaFaltantes:'0'}],extracao:[{rota:'A1_AM1',doca:'62'}]};
assert.equal(run('packageClosureModel(source).useFinal'), false);
assert.equal(run('packageClosureModel(source).aMais'), 2);
ctx.source.baseAduana[0].aduanaAMais = '0';assert.equal(run('packageClosureModel(source).routes'),0);
if (process.argv[2]) {
 ctx.csv = fs.readFileSync(process.argv[2], 'utf8');
 const real = run('parseFinalAuditCsv(csv)');
 assert.equal(real.packages,526);assert.equal(real.rows.length,10);
 assert.equal(real.rows.reduce((n,r)=>n+r.aMais,0),1);
 assert.equal(real.rows.reduce((n,r)=>n+r.faltantes,0),5);
 assert.equal(real.rows.reduce((n,r)=>n+r.corretos,0),520);
 console.log('Arquivo enviado: 526 pacotes únicos, 10 rotas, 1 a mais, 5 faltantes, 520 corretos.');
}
console.log('OK: sintaxe, deduplicação, atualização por horário, datas, estados, setores, IDs conflitantes e fonte ao vivo/final.');
assert.equal(parsed.rows[0].ocorrencias.length,2);
assert.equal(parsed.rows[0].ocorrencias[0].shipmentId,'1');
assert.equal(parsed.rows[0].ocorrencias[1].estado,'faltantes');
const output = {innerHTML:''};ctx.document={getElementById:()=>output};
ctx.data={data:'30/09/2026',docas:92,extracao:[{rota:'A1_AM1',idRota:'123',doca:'23',onda:'Onda 1'}],aduanaFechamentoFinal:{...parsed,fileName:'teste.csv'},responsaveisPorLado:{'Lado Central':{coordenador:'Coord Teste',ps:'PS Teste'}}};
run('renderPackageClosure()');
assert.ok(output.innerHTML.includes('Coord Teste'));assert.ok(output.innerHTML.includes('PS Teste'));
assert.ok(output.innerHTML.includes('ID do pacote'));assert.ok(output.innerHTML.includes('30/09/2026 10:01:00'));
assert.equal((output.innerHTML.match(/A1_AM1/g)||[]).length,2);
assert.equal(JSON.parse(JSON.stringify(parsed)).rows[0].ocorrencias[0].shipmentId,'1');
console.log('OK: IDs individuais, horários, rota, setor e responsáveis no fechamento final.');
